env:
  commonjs: true
  es6: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  sourceType: module
plugins:
  - "@typescript-eslint"
extends:
  - airbnb-base
  - prettier
rules:
  "class-methods-use-this": 0
  "default-case": 0
  "import/extensions": 0
  "import/no-extraneous-dependencies": 0
  "import/no-unresolved": 0
  "import/prefer-default-export": 0
